Repository midudev/la-velada-web-oficial, pull requests merged in 2024-03, with the labels that each got.

#271 Optimizar fuente Atomic de 373.56KB a 217.77KB
  public/fonts/atomic.woff2
Labels: duplicate

#333 Mejoras de UI al error 404 Not Found
  src/pages/404.astro
  src/sections/Error.astro
Labels: enhancement

#331 Add: Animacion svg del logo principas
  src/components/LogoAnimado.astro
  src/sections/Hero.astro
Labels: conflictos

#404 Fix: Center TwitchLogo
  src/sections/Info.astro
Labels: diseño

#424 Ajusta color `hover` de algunos elementos
  src/components/LiteYouTube.astro
  src/sections/Footer.astro
Labels: diseño

#412 (AGAIN) Change calendar's dropdown font
  public/css/add-to-calendar.css
Labels: diseño

#416 change player bar
  src/components/LiteYouTube.astro
Labels: pensando-si-añadirlo, diseño

#405 fix(#401): resizing bug on resize
  src/components/LiteYouTube.astro
Labels: esperando-respuesta

#246 editado el Date y el Countdown para que se parezcan al del Figma
  src/components/Date.astro
  src/pages/index.astro
  src/sections/Countdown.astro
Labels: conflictos

#370 Feature añadiendo la sección de los links (issues #323)
  public/img/event/combates.png
  public/img/event/combates.webp
  public/img/event/entradas.png
  public/img/event/entradas.webp
  public/img/event/evento.png
  public/img/event/evento.webp
  public/img/event/pronosticos.png
  public/img/event/pronosticos.webp
  src/components/ImageOverlay.astro
  src/pages/index.astro
  src/sections/Boxing.astro
Labels: enhancement, esperando-respuesta

#345 Enhanced: Improved Konami code support
  public/img/cursor/among-us.cur
  public/img/cursor/boxing-glove.cur
  public/img/cursor/lol.cur
  src/components/KonamiCode.astro
  src/consts/dom-selector.ts
  src/consts/konami-codes.ts
  src/function/konami.ts
Labels: pensando-si-añadirlo

#447 docs: Added demo script for `nvm use` on `cd <path>`
  README.md
Labels: documentation, pensando-si-añadirlo

#442 fix(action): action component responsive
  src/components/Action.astro
  src/components/CalendarButton.astro
  src/sections/PrincipalDate.astro
Labels: conflictos

#484 Id boxer description
  src/pages/boxers/[id].astro
  src/sections/SelectYourBoxer.astro
Labels: diseño

#491 Full Responsive Menu/Header Figma
  public/img/lvda.webp
  src/components/FooterContent.astro
  src/components/HamburgerButton.astro
  src/components/Header.astro
  src/components/HeroLogo.astro
  src/components/SocialButtons.astro
  src/layouts/Layout.astro
  src/sections/Footer.astro
Labels: enhancement

#480 Cambio de propiedades de CSS por clases de Tailwind en SelectYourBoxer
  src/sections/SelectYourBoxer.astro
Labels: diseño

#504 El error de la última versión de Astro se encuentra en devToolbar, que viene por defecto activado.
  package.json
Labels: conflictos

#314 feature: add SectionTitle Component
  src/components/SectionTitle.astro
Labels: duplicate

#548 Foto, información y redes sociales del boxeador
  src/components/BoxerDetailInfo.astro
  src/consts/boxers.ts
  src/consts/combats.ts
  src/pages/api/builtwith.json.ts
  src/pages/api/combats/get-combat-by-boxer-id.json.ts
  src/pages/boxers/[id].astro
  src/sections/SelectYourBoxer.astro
Labels: esperando-respuesta

#566 fix: Color on BoxerDetailInfo title Rival/es
  src/components/BoxerDetailInfo.astro
Labels: diseño

#588 Boxer Responsive Information
  src/components/BoxerDetailInfo.astro
  src/pages/boxers/[id].astro
Labels: diseño

#574 Marcar oponentes y aliados cuando se hace hover usando filtros
  src/components/ColumnBoxers.astro
  src/consts/boxers.ts
  src/sections/SelectYourBoxer.astro
Labels: diseño

#620 BoxerSocialLink Hover
  src/components/BoxerSocialLink.astro
Labels: diseño

#621 fix: responsive boxers page
  src/pages/boxers/[id].astro
Labels: conflictos

#613 [FEAT] recuperada PR 512
  src/sections/SelectYourBoxer.astro
Labels: conflictos

#633 add folagor links
  src/consts/boxers.ts
Labels: conflictos

#635 Add social media links for boxer Peldanyos
  src/consts/boxers.ts
Labels: conflictos

#701 correccion de nombre de boxeador Carreraaa
  public/img/matches/1-agustin-51-vs-carreraaa.webp
  public/img/matches/og-1-agustin-51-vs-carreraaa-min.webp
  public/img/matches/title-1-agustin-51-vs-carreraaa.webp
Labels: diseño

#707 FIX: Improve combat page effects #688
  src/pages/combates/index.astro
Labels: diseño

#745 Icono scroll debajo select boxer // option 2
  src/icons/horizontalScroll.astro
  src/sections/SelectYourBoxer.astro
Labels: diseño

#762 Refactor BoxerDetailInfoRival component layout to avoid spaces
  src/components/BoxerDetailInfoRival.astro
Labels: diseño

#768 Tabla comparativa 1vs1 en página de combates
  src/pages/combates/[id].astro
  src/sections/CombatFeatures.astro
Labels: enhancement
