Repository midudev/la-velada-web-oficial, pull requests merged in 2025-04, with the labels that each got.

#1152 Replace static pairings with dynamic data-versus logic
  src/components/BoxerCard.astro
  src/components/FighterSelector.astro
  src/components/HeroCss.astro
  src/sections/Hero.astro
Labels: aprobado-para-mergear

#1112 Feature/ Animate Fighter Fade Text
  src/sections/Hero.astro
Labels: conflictos, aprobado-para-mergear

#1312 Clean up unused sponsors SVGs and fixed CocaCola SVG.
  src/assets/sponsors/CocaCola.svg
  src/assets/sponsors/ElPozo.svg
  src/assets/sponsors/GShock.svg
  src/assets/sponsors/Prime.svg
  src/assets/sponsors/PrimeH.svg
Labels: conflictos

#1367 fix: correct blurred images size to not overflow
  src/components/LiteYouTube.astro
  src/sections/Entradas.astro
Labels: bug
